{{- if .Values.certs.grpc.create }}
{{ $fullname := include "fullname" . }}
{{- if .Values.certs.legacyApi }}
apiVersion: certmanager.k8s.io/v1alpha1
{{- else }}
apiVersion: cert-manager.io/v1alpha2
{{- end }}
kind: Certificate
metadata:
  name: {{ $fullname }}-grpc-server-cert
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  secretName: {{ .Values.certs.grpc.server.secretName }}
  issuerRef:
    name: dex-grpc-cert-issuer
    kind: Issuer
  commonName: dex.{{ .Release.Namespace }}
  dnsName:
  - dex.{{ .Release.Namespace }}
{{- end }}
