{{- if .Values.certs.grpc.create }}
{{ $fullname := include "fullname" . }}
{{- if .Values.certs.legacyApi }}
apiVersion: certmanager.k8s.io/v1alpha1
{{- else }}
apiVersion: cert-manager.io/v1alpha2
{{- end }}
kind: Issuer
metadata:
  name: dex-grpc-cert-issuer
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  ca:
    secretName: {{ .Values.certs.grpc.ca.secretName }}
{{- end }}
